export const SEEK_TIME = 5;

export const MAYBE_SUBREDDITS = [
  'DramaFreeBJJ',
  'fightporn',
  'tooktoomuch',
];

export const CRINGE_SUBREDDITS = [
  'crappymusic',
  'CringeTikToks'
];

export const ANIMAL_SUBREDDITS = [
  'AnimalsBeingDerps',
  'animalsdoingstuff',
  'Catculations',
  'cats',
  'dogvideos',
  'FunnyAnimals',
  'holdmycatnip',
  'WhatsWrongWithYourDog',
]

export const DEFAULT_SUBREDDITS = [
  'AbruptChaos',
  'AccidentalSlapStick',
  'ActualPublicFreakouts',
  'BeAmazed',
  'bizarrelife',
  'blackmagicfuckery',
  'blursed_videos',
  'Bossfight',
  'CatastrophicFailure',
  'ContagiousLaughter',
  'CoupleMemes',
  'CrazyFuckingVideos',
  'Damnthatsinteresting',
  'dankvideos',
  'dashcams',
  'discordVideos',
  'Fauxmoi',
  'fixedbytheduet',
  'foundsatan',
  'FUCKYOUINPARTICULAR',
  'funny',
  'GamePhysics',
  'GuysBeingDudes',
  'holdmycosmo',
  'HolUp',
  'HumansBeingBros',
  'iamatotalpieceofshit',
  'idiotsincars',
  'ImTheMainCharacter',
  'interestingasfuck',
  'KidsAreFuckingStupid',
  'MadeMeSmile',
  'maybemaybemaybe',
  'MemeVideos',
  'NatureIsFuckingLit',
  'nextfuckinglevel',
  'nonononoyes',
  'oddlysatisfying',
  'PeopleFuckingDying',
  'pranks',
  'PublicFreakout',
  'roadcam',
  'Satisfyingasfuck',
  'ScienceNcoolThings',
  'SipsTea',
  'Smilepleasse',
  'StandUpComedy',
  'StrangeAndFunny',
  'SweatyPalms',
  'ThatsInsane',
  'therewasanattempt',
  'theviralthings',
  'thisismylifenow',
  'tikTokCringe',
  'toptalent',
  'UNBGBBIIVCHIDCTIICBG',
  'Unexpected',
  'WatchPeopleDieInside',
  'Whatcouldgowrong',
  'whenthe',
  'WinStupidPrizes',
  'yesyesyesyesno',
  'youseeingthisshit',
  ...ANIMAL_SUBREDDITS,
  ...CRINGE_SUBREDDITS,
  ...MAYBE_SUBREDDITS,
]
